services:
  - type: web
    name: linkedin-post-agent-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: GOOGLE_API_KEY
        sync: false
      - key: LINKEDIN_EMAIL
        sync: false
      - key: LINKEDIN_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 10000 